# Generated by Django 6.0.4 on 2026-04-24 21:27

import config.fields
import django.db.models.deletion
import its_now_api.its_now.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItsNowUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_meditations_used_this_month', models.PositiveIntegerField(default=0)),
                ('usage_month_start', models.DateField(default=its_now_api.its_now.models.current_usage_month_start)),
                ('total_meditations_generated', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='its_now_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', config.fields.PublicIdField(blank=True, db_index=True, default=config.fields.generate_random_id, help_text='Public-facing random ID', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('used_free_generation', models.BooleanField(default=False)),
                ('photo_inputs', models.JSONField(default=list)),
                ('present_moment_context', models.JSONField(blank=True, default=dict)),
                ('scene_description', models.TextField(blank=True)),
                ('quality_visualization', models.CharField(blank=True, max_length=255)),
                ('audio_filename', models.CharField(blank=True, max_length=255)),
                ('audio_storage_key', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('its_now_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='its_now.itsnowuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
