# Generated by Django 5.2.10 on 2026-03-28 18:29

import camera_roll_sounds_api.camera_roll_sounds.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_roll_sounds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='used_free_generation',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CameraRollSoundsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_meditations_used_this_month', models.PositiveIntegerField(default=0)),
                ('usage_month_start', models.DateField(default=camera_roll_sounds_api.camera_roll_sounds.models.current_usage_month_start)),
                ('total_meditations_generated', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='camera_roll_sounds_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='generationjob',
            name='camera_roll_sounds_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='camera_roll_sounds.camerarollsoundsuser'),
        ),
    ]
