# Generated by Django 5.2.10 on 2026-03-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_roll_sounds', '0002_generationjob_used_free_generation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='audio_storage_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
